# Site settings
title: Matt's Super Cool Blog
email: mtlewandowsk@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first Jekyll blog and I hope to update it regularly. 
baseurl: "/Matt/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  mtlewandowsk89

# Build settings
markdown: kramdown
